### PR TITLE
Ensure that all downloaded model files are md5sum-checked.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by xuhdev** [comment]
https://github.com/IBM/MAX-Text-Summarizer/pull/19 demonstrates how these lines can discover errrors.

**Review by ptitzler — COMMENTED** [review]
Wouldn't it be better to perform this test directly in our Travis CI test suite instead of every time somebody builds a Docker image?

**Comment by xuhdev** [comment]
Since md5sum is checked for downloading files, it seems making sense to make sure that all files are md5sum-checked when building Docker image.

But I'm OK with either way. I do not have a strong opinion on this.

**Comment by xuhdev** [comment]
@ptitzler It looks like if we put this check in CI, we would have to redownload the model file in the CI environment, and we have to repeat the same `wget` + URL command written in Dockerfile (a bit redundant). Would that be acceptable?

**Comment by bdwyer2** [comment]
@xuhdev and I discussed offline that we should migrate to SHA512

**Comment by xuhdev** [comment]
Has anything similar been merged? This PR intends to make sure that everything that has been downloaded are checksum checked.

**Comment by djalova** [comment]
Oh I thought the PR that changed the Dockerfile to SHA512 already handled this. I'll reopen.

**Comment by gdequeiroz** [comment]
Can we merge this? (cc @MLnick @ptitzler)

**Pull request closed without merging**
