### PR TITLE
Update config and model metadata

### PR DESCRIPTION
**Pull request by splovyt**
Move the model's metadata to the config file and add more descriptive text.

### CODE REVIEW

**Comment by djalova** [comment]
I'm not sure if we should move the metadata to config if we're just going to import it in the model. Also if we have multiple models, then we have to put multiple metadata in the config.

**Comment by splovyt** [comment]
@djalova thanks for the feedback. 

The reason I personally wanted to move it is because all the subjective naming etc happens in `config.py` so it makes for a better overview. I did this in the models I published so I wanted to propose it for the skeleton as well. 

It's a subjective decision so if nobody is in favor we can just close this PR 🙂. Thanks for the review!

**Comment by MLnick** [comment]
We did originally have it in the config file... I don't have a strong opinion either way but I do like to keep as much of the actual "changeable config" in the config file itself

**Comment by splovyt** [comment]
> We did originally have it in the config file... I don't have a strong opinion either way but I do like to keep as much of the actual "changeable config" in the config file itself

I agree. That's the reason why the metadata of my models are in my config 🙂 . The final decision is yours Nick!

**Comment by ptitzler** [comment]
There are good arguments for and against such a change, but I'm leaning towards against it.

**Comment by MLnick** [comment]
We had already made the change previously to put the metadata into the model itself. If I recall the reasoning there is that we were just always importing the metadata from the config directly anyway as Daniel said. Let's leave things as is for now (there are enough other changes happening as it is) @splovyt

**Pull request closed without merging**
